# Generated by Django 5.2.3 on 2025-06-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='fechaDeCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
